[package]
name = "ivadsiuls/zaphy"
description = "Zaphy is a easy-to-use game framework"
license = "MIT"
version = "2.1.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Net = "sleitnick/net@0.2.0"
Maid = "nightcycle/maid@2.2.2"
Signal = "sleitnick/signal@2.0.3"