[package]
name = "ivadsiuls/zaphy"
description = """
Zaphy is a easy-to-use game framework.

Full documentation at:
https://froststarinteractive.github.io/zaphy/
"""
license = "MIT"
version = "2.1.6"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Net = "sleitnick/net@0.2.0"
Maid = "nightcycle/maid@2.2.2"
Signal = "sleitnick/signal@2.0.3"